openapi: 3.1.0
info:
  title: GPT Drive Agent
  version: "1.6"          # ← incrément pour purger le cache

servers:
  - url: https://web-production-da670.up.railway.app

paths:
  /drive/list:
    get:
      operationId: listFiles
      summary: Lister les fichiers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string

  /drive/create-folder:
    post:
      operationId: createFolder
      summary: Créer un sous-dossier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Nom du dossier
      responses:
        "201":
          description: Dossier créé
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string

  /drive/upload:
    post:
      operationId: uploadFile
      summary: Téléverser un fichier
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - file
              properties:
                name:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: Fichier créé
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string

  /drive/update/{file_id}:
    patch:
      operationId: updateFile
      summary: Renommer ou déplacer un fichier
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_name:
                  type: string
                new_parent_id:
                  type: string
              additionalProperties: false
      responses:
        "200":
          description: Fichier mis à jour
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string

  /drive/file/{file_id}:
    delete:
      operationId: deleteFile
      summary: Supprimer un fichier
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Fichier supprimé
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - id
                properties:
                  status:
                    type: string
                  id:
                    type: string
