openapi: 3.0.1
info:
  title: GPT Drive Agent
  version: "1.3"

servers:
  - url: https://web-production-da670.up.railway.app

paths:
  /drive/list:
    get:
      operationId: listFiles
      summary: Lister les fichiers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string

  /drive/create-folder:
    post:
      operationId: createFolder
      summary: Créer un sous‑dossier
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Dossier créé
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string

  /drive/upload:
    post:
      operationId: uploadFile
      summary: Téléverser un fichier
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Fichier créé
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string

  /drive/update/{file_id}:
    patch:
      operationId: updateFile
      summary: Renommer ou déplacer un fichier
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                new_name:
                  type: string
                new_parent_id:
                  type: string
      responses:
        "200":
          description: Fichier mis à jour
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  parents:
                    type: array
                    items:
                      type: string

  /drive/file/{file_id}:
    delete:
      operationId: deleteFile
      summary: Supprimer un fichier
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Fichier supprimé
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  id:
                    type: string
